### ISSUE TITLE
Deprecated `page` parameter

### ISSUE THREAD

**Issue by 66Bunz** [opsdisk/pygumroad#8]
When trying to get all sales this error is thrown:
`{"status":400,"error":"The 'page' parameter is deprecated. Please use 'page_key' instead: https://app.gumroad.com/api#sales"}`

Can you fix this @opsdisk?

**Comment by opsdisk** [comment]
Thanks for taking the time to submit an issue @66Bunz - I don't use this library myself anymore, but if you submit a PR for it I can take a look.

**Comment by 66Bunz** [comment]
ah okok, I'll take a look

**Comment by 66Bunz** [comment]
@opsdisk #9
